// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of frame_i
//        bit 31~0 - frame_i[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of frame_o
//        bit 31~0 - frame_o[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBACKSUB_AXILITES_ADDR_FRAME_I_DATA 0x10
#define XBACKSUB_AXILITES_BITS_FRAME_I_DATA 32
#define XBACKSUB_AXILITES_ADDR_FRAME_O_DATA 0x18
#define XBACKSUB_AXILITES_BITS_FRAME_O_DATA 32

// CRTL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of learningRate
//        bit 31~0 - learningRate[31:0] (Read/Write)
// 0x14 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBACKSUB_CRTL_BUS_ADDR_LEARNINGRATE_DATA 0x10
#define XBACKSUB_CRTL_BUS_BITS_LEARNINGRATE_DATA 32

