// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbacksub.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBacksub_CfgInitialize(XBacksub *InstancePtr, XBacksub_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBacksub_Set_frame_i(XBacksub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_I_DATA, Data);
}

u32 XBacksub_Get_frame_i(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_I_DATA);
    return Data;
}

void XBacksub_Set_frame_o(XBacksub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_O_DATA, Data);
}

u32 XBacksub_Get_frame_o(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Axilites_BaseAddress, XBACKSUB_AXILITES_ADDR_FRAME_O_DATA);
    return Data;
}

void XBacksub_Set_learningRate(XBacksub *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBacksub_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_LEARNINGRATE_DATA, Data);
}

u32 XBacksub_Get_learningRate(XBacksub *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBacksub_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XBACKSUB_CRTL_BUS_ADDR_LEARNINGRATE_DATA);
    return Data;
}

