// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of frame_in
//        bit 31~0 - frame_in[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of frame_out
//        bit 31~0 - frame_out[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of init
//        bit 0  - init[0] (Read/Write)
//        others - reserved
// 0x24 : reserved
// 0x28 : Data signal of bgmodel
//        bit 31~0 - bgmodel[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBGSUB_AXILITES_ADDR_FRAME_IN_DATA  0x10
#define XBGSUB_AXILITES_BITS_FRAME_IN_DATA  32
#define XBGSUB_AXILITES_ADDR_FRAME_OUT_DATA 0x18
#define XBGSUB_AXILITES_BITS_FRAME_OUT_DATA 32
#define XBGSUB_AXILITES_ADDR_INIT_DATA      0x20
#define XBGSUB_AXILITES_BITS_INIT_DATA      1
#define XBGSUB_AXILITES_ADDR_BGMODEL_DATA   0x28
#define XBGSUB_AXILITES_BITS_BGMODEL_DATA   32

