// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

extern void bgsub (
unsigned char frame_in[76800],
unsigned char frame_out[76800],
bool init,
float bgmodel[614400]);
